"""Seed Data for Enterprise Active Directory Structure."""

from typing import Dict, List
from src.infra.ad_directory.schema import (
    ADComputer,
    ADGroup,
    ADOrganizationalUnit,
    ADUser,
)

BASE_DN = "DC=corp,DC=enterprise,DC=local"

DEFAULT_ORGANIZATIONAL_UNITS: List[ADOrganizationalUnit] = [
    ADOrganizationalUnit(
        name="Domain Controllers",
        dn=f"OU=Domain Controllers,{BASE_DN}",
        description="Domain Controllers OU containing Active Directory KDCs",
        guid="ad-ou-001",
    ),
    ADOrganizationalUnit(
        name="Administration",
        dn=f"OU=Administration,{BASE_DN}",
        description="High privilege administrative accounts and groups (Tier 0)",
        guid="ad-ou-002",
    ),
    ADOrganizationalUnit(
        name="Tier-0-Admins",
        dn=f"OU=Tier-0-Admins,OU=Administration,{BASE_DN}",
        description="Domain and Enterprise Administrators",
        guid="ad-ou-003",
    ),
    ADOrganizationalUnit(
        name="Identities",
        dn=f"OU=Identities,{BASE_DN}",
        description="Parent OU for all enterprise human and service identities",
        guid="ad-ou-004",
    ),
    ADOrganizationalUnit(
        name="Enterprise-Users",
        dn=f"OU=Enterprise-Users,OU=Identities,{BASE_DN}",
        description="Standard corporate employees and staff",
        guid="ad-ou-005",
    ),
    ADOrganizationalUnit(
        name="Service-Accounts",
        dn=f"OU=Service-Accounts,OU=Identities,{BASE_DN}",
        description="Service accounts running backend daemons with SPNs",
        guid="ad-ou-006",
    ),
    ADOrganizationalUnit(
        name="Computers",
        dn=f"OU=Computers,{BASE_DN}",
        description="Domain joined computer and server assets",
        guid="ad-ou-007",
    ),
    ADOrganizationalUnit(
        name="Tier-1-Servers",
        dn=f"OU=Tier-1-Servers,OU=Computers,{BASE_DN}",
        description="Enterprise application and database servers",
        guid="ad-ou-008",
    ),
    ADOrganizationalUnit(
        name="Tier-2-Workstations",
        dn=f"OU=Tier-2-Workstations,OU=Computers,{BASE_DN}",
        description="Corporate end-user workstations and laptops",
        guid="ad-ou-009",
    ),
    ADOrganizationalUnit(
        name="Security-Groups",
        dn=f"OU=Security-Groups,{BASE_DN}",
        description="Security and distribution groups",
        guid="ad-ou-010",
    ),
]

DEFAULT_GROUPS: List[ADGroup] = [
    ADGroup(
        sAMAccountName="Domain Admins",
        distinguishedName=f"CN=Domain Admins,OU=Administration,{BASE_DN}",
        description="Designated administrators of the domain (Tier 0)",
        members=["Administrator", "da_johnson"],
        is_privileged=True,
    ),
    ADGroup(
        sAMAccountName="Enterprise Admins",
        distinguishedName=f"CN=Enterprise Admins,OU=Administration,{BASE_DN}",
        description="Designated administrators of the enterprise forest (Tier 0)",
        members=["Administrator", "ea_miller"],
        is_privileged=True,
    ),
    ADGroup(
        sAMAccountName="Server Operators",
        distinguishedName=f"CN=Server Operators,OU=Security-Groups,{BASE_DN}",
        description="Members can administer domain servers (Tier 1)",
        members=["bwayne"],
        is_privileged=True,
    ),
    ADGroup(
        sAMAccountName="HelpDesk",
        distinguishedName=f"CN=HelpDesk,OU=Security-Groups,{BASE_DN}",
        description="First-line IT support specialists (Tier 2)",
        members=["bwayne"],
        is_privileged=False,
    ),
    ADGroup(
        sAMAccountName="Finance-Department",
        distinguishedName=f"CN=Finance-Department,OU=Security-Groups,{BASE_DN}",
        description="Corporate finance and accounting personnel",
        members=["jdoe"],
        is_privileged=False,
    ),
    ADGroup(
        sAMAccountName="HR-Department",
        distinguishedName=f"CN=HR-Department,OU=Security-Groups,{BASE_DN}",
        description="Human Resources department staff",
        members=["asmith"],
        is_privileged=False,
    ),
    ADGroup(
        sAMAccountName="Domain Users",
        distinguishedName=f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        description="All domain users",
        members=[
            "Administrator",
            "da_johnson",
            "ea_miller",
            "jdoe",
            "asmith",
            "bwayne",
            "svc_sql",
            "svc_backup",
        ],
        is_privileged=False,
    ),
]

DEFAULT_USERS: List[ADUser] = [
    ADUser(
        sAMAccountName="Administrator",
        userPrincipalName="Administrator@corp.enterprise.local",
        displayName="Built-in Administrator",
        distinguishedName=f"CN=Administrator,OU=Tier-0-Admins,OU=Administration,{BASE_DN}",
        mail="administrator@corp.enterprise.local",
        department="IT Security",
        title="Built-in Domain Administrator",
        memberOf=[
            f"CN=Domain Admins,OU=Administration,{BASE_DN}",
            f"CN=Enterprise Admins,OU=Administration,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=True,
        admin_tier=0,
        password_hash="$2b$12$labPasswordHashAdministratorDemoOnly",
    ),
    ADUser(
        sAMAccountName="da_johnson",
        userPrincipalName="da_johnson@corp.enterprise.local",
        displayName="David Johnson (Domain Admin)",
        distinguishedName=f"CN=David Johnson,OU=Tier-0-Admins,OU=Administration,{BASE_DN}",
        mail="djohnson.admin@corp.enterprise.local",
        department="Infrastructure",
        title="Lead Enterprise Infrastructure Architect",
        memberOf=[
            f"CN=Domain Admins,OU=Administration,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=True,
        admin_tier=0,
        password_hash="$2b$12$labPasswordHashDavidJohnsonDemoOnly",
    ),
    ADUser(
        sAMAccountName="ea_miller",
        userPrincipalName="ea_miller@corp.enterprise.local",
        displayName="Emma Miller (Enterprise Admin)",
        distinguishedName=f"CN=Emma Miller,OU=Tier-0-Admins,OU=Administration,{BASE_DN}",
        mail="emiller.admin@corp.enterprise.local",
        department="Information Security",
        title="Chief Information Security Officer",
        memberOf=[
            f"CN=Enterprise Admins,OU=Administration,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=True,
        admin_tier=0,
        password_hash="$2b$12$labPasswordHashEmmaMillerDemoOnly",
    ),
    ADUser(
        sAMAccountName="jdoe",
        userPrincipalName="jdoe@corp.enterprise.local",
        displayName="John Doe",
        distinguishedName=f"CN=John Doe,OU=Enterprise-Users,OU=Identities,{BASE_DN}",
        mail="jdoe@corp.enterprise.local",
        department="Finance",
        title="Senior Financial Analyst",
        memberOf=[
            f"CN=Finance-Department,OU=Security-Groups,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=False,
        password_hash="$2b$12$labPasswordHashJohnDoeDemoOnly",
    ),
    ADUser(
        sAMAccountName="asmith",
        userPrincipalName="asmith@corp.enterprise.local",
        displayName="Alice Smith",
        distinguishedName=f"CN=Alice Smith,OU=Enterprise-Users,OU=Identities,{BASE_DN}",
        mail="asmith@corp.enterprise.local",
        department="Human Resources",
        title="HR Operations Lead",
        memberOf=[
            f"CN=HR-Department,OU=Security-Groups,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=False,
        password_hash="$2b$12$labPasswordHashAliceSmithDemoOnly",
    ),
    ADUser(
        sAMAccountName="bwayne",
        userPrincipalName="bwayne@corp.enterprise.local",
        displayName="Bruce Wayne",
        distinguishedName=f"CN=Bruce Wayne,OU=Enterprise-Users,OU=Identities,{BASE_DN}",
        mail="bwayne@corp.enterprise.local",
        department="IT Operations",
        title="Senior Systems Support Technician",
        memberOf=[
            f"CN=HelpDesk,OU=Security-Groups,{BASE_DN}",
            f"CN=Server Operators,OU=Security-Groups,{BASE_DN}",
            f"CN=Domain Users,OU=Security-Groups,{BASE_DN}",
        ],
        is_admin=False,
        admin_tier=2,
        password_hash="$2b$12$labPasswordHashBruceWayneDemoOnly",
    ),
    ADUser(
        sAMAccountName="svc_sql",
        userPrincipalName="svc_sql@corp.enterprise.local",
        displayName="Service Account - MSSQL Database",
        distinguishedName=f"CN=svc_sql,OU=Service-Accounts,OU=Identities,{BASE_DN}",
        mail="svc_sql@corp.enterprise.local",
        department="Database Operations",
        title="MSSQL Database Engine Service Identity",
        memberOf=[f"CN=Domain Users,OU=Security-Groups,{BASE_DN}"],
        servicePrincipalNames=[
            "MSSQLSvc/db01.corp.enterprise.local:1433",
            "MSSQLSvc/db01.corp.enterprise.local",
        ],
        is_admin=False,
        password_hash="$2b$12$labPasswordHashServiceSqlDemoOnly",
    ),
    ADUser(
        sAMAccountName="svc_backup",
        userPrincipalName="svc_backup@corp.enterprise.local",
        displayName="Service Account - Enterprise Backup",
        distinguishedName=f"CN=svc_backup,OU=Service-Accounts,OU=Identities,{BASE_DN}",
        mail="svc_backup@corp.enterprise.local",
        department="Infrastructure Operations",
        title="Backup Orchestration Service Identity",
        memberOf=[f"CN=Domain Users,OU=Security-Groups,{BASE_DN}"],
        servicePrincipalNames=[
            "BackupSvc/backup01.corp.enterprise.local",
        ],
        is_admin=False,
        password_hash="$2b$12$labPasswordHashServiceBackupDemoOnly",
    ),
]

DEFAULT_COMPUTERS: List[ADComputer] = [
    ADComputer(
        sAMAccountName="DC01$",
        distinguishedName=f"CN=DC01,OU=Domain Controllers,{BASE_DN}",
        dNSHostName="dc01.corp.enterprise.local",
        operatingSystem="Windows Server 2022 Datacenter",
        ipAddress="172.28.20.10",
        memberOf=[f"CN=Domain Controllers,OU=Domain Controllers,{BASE_DN}"],
    ),
    ADComputer(
        sAMAccountName="LINUX-SRV01$",
        distinguishedName=f"CN=LINUX-SRV01,OU=Tier-1-Servers,OU=Computers,{BASE_DN}",
        dNSHostName="linux-srv01.corp.enterprise.local",
        operatingSystem="Ubuntu 22.04 LTS Linux",
        ipAddress="172.28.20.15",
        memberOf=[f"CN=Domain Computers,OU=Computers,{BASE_DN}"],
    ),
    ADComputer(
        sAMAccountName="WKSTN-WIN10$",
        distinguishedName=f"CN=WKSTN-WIN10,OU=Tier-2-Workstations,OU=Computers,{BASE_DN}",
        dNSHostName="wkstn-win10.corp.enterprise.local",
        operatingSystem="Windows 10 Enterprise",
        ipAddress="172.28.20.25",
        memberOf=[f"CN=Domain Computers,OU=Computers,{BASE_DN}"],
    ),
]
